In [24]:
import pandas as pd

data = pd.read_csv('/mnt/c/Users/ouyangkang/Desktop/multi_infect_to_human.csv')

In [25]:
data

,VirusFamily,Infect_MultiFamily_Except_hominidae,IMFE_Infect_human,One_Family,OF_Infect_human
0,Adenoviridae,24,3,60,4
1,Anelloviridae,11,7,37,1
2,Arenaviridae,13,7,37,3
3,Astroviridae,12,4,9,3
4,Bornaviridae,5,1,6,1
5,Caliciviridae,6,3,7,1
6,Circoviridae,14,3,55,1
7,Coronaviridae,23,6,18,0
8,Filoviridae,6,6,5,0
9,Flaviviridae,50,37,36,7
10,Hantaviridae,12,10,38,5
11,Hepeviridae,4,2,1,0
12,Herpesviridae,42,9,57,6
13,Nairoviridae,10,7,6,1
14,Orthomyxoviridae,7,5,2,0
15,Papillomaviridae,9,0,80,5
16,Paramyxoviridae,36,16,36,4
17,Parvoviridae,16,7,79,2
18,Peribunyaviridae,44,30,24,6
19,Phenuiviridae,15,11,13,2
20,Picornaviridae,37,18,87,6
21,Pneumoviridae,4,2,0,0
22,Polyomaviridae,5,1,62,2
23,Poxviridae,18,8,26,5
24,Reoviridae,36,15,12,1
25,Rhabdoviridae,32,14,34,2
26,Togaviridae,25,22,3,2

In [29]:
trans_family = pd.DataFrame(columns=['Type','Ratio'])
n = 0
for family in list(data['VirusFamily']):
    multi = round(int(data[data['VirusFamily']== family]['IMFE_Infect_human'])/int(data[data['VirusFamily']== family]['Infect_MultiFamily_Except_hominidae']),3)
    if int(data[data['VirusFamily']== family]['OF_Infect_human']) != 0:
        one = round(int(data[data['VirusFamily']== family]['OF_Infect_human'])/int(data[data['VirusFamily']== family]['One_Family']),3)
    else:
        one = 0
    trans_family.loc[(n*2)+0] = ['Trans_Mulit',multi]
    trans_family.loc[(n*2)+1] = ['One',one]
    n += 1

In [30]:
trans_family

           Type  Ratio
0   Trans_Mulit  0.125
1           One  0.067
2   Trans_Mulit  0.636
3           One  0.027
4   Trans_Mulit  0.538
5           One  0.081
6   Trans_Mulit  0.333
7           One  0.333
8   Trans_Mulit  0.200
9           One  0.167
10  Trans_Mulit  0.500
11          One  0.143
12  Trans_Mulit  0.214
13          One  0.018
14  Trans_Mulit  0.261
15          One  0.000
16  Trans_Mulit  1.000
17          One  0.000
18  Trans_Mulit  0.740
19          One  0.194
20  Trans_Mulit  0.833
21          One  0.132
22  Trans_Mulit  0.500
23          One  0.000
24  Trans_Mulit  0.214
25          One  0.105
26  Trans_Mulit  0.700
27          One  0.167
28  Trans_Mulit  0.714
29          One  0.000
30  Trans_Mulit  0.000
31          One  0.062
32  Trans_Mulit  0.444
33          One  0.111
34  Trans_Mulit  0.438
35          One  0.025
36  Trans_Mulit  0.682
37          One  0.250
38  Trans_Mulit  0.733
39          One  0.154
40  Trans_Mulit  0.486
41          One  0.069
42  Trans_Mulit  0.500
43          One  0.000
44  Trans_Mulit  0.200
45          One  0.032
46  Trans_Mulit  0.444
47          One  0.192
48  Trans_Mulit  0.417
49          One  0.083
50  Trans_Mulit  0.438
51          One  0.059
52  Trans_Mulit  0.880
53          One  0.667

In [31]:
trans_family.to_csv('/mnt/c/Users/ouyangkang/Desktop/trans_family0210.csv',index=None)