In [15]:
import pandas as pd

In [16]:
data = pd.read_csv("/mnt/d/dailywork/Mouse_brain/diffpeak_annotation.csv")

In [17]:
data = data[data.Log2FC > 0]
data.head(5)

,Unnamed: 0,X,Log2FC,Mean,FDR,Pval,MeanDiff,AUC,MeanBGD,Time_CT_I,CT_I,group
1,1,chr1_11033445_11033945,1.169023,0.079593,0.696626,0.010052,0.045307,0.514972,0.034286,Day 1_AC,AC,Day 1_AC
3,3,chr1_20069639_20070139,1.414674,0.042238,0.696626,0.028092,0.027644,0.508984,0.014593,Day 1_AC,AC,Day 1_AC
6,6,chr1_36303340_36303840,1.294420,0.099489,0.696626,0.016109,0.060112,0.516284,0.039377,Day 1_AC,AC,Day 1_AC
10,10,chr1_39069775_39070275,3.600718,0.050492,0.347446,0.000244,0.048165,0.515008,0.002327,Day 1_AC,AC,Day 1_AC
11,11,chr1_39196691_39197191,1.831633,0.041386,0.696626,0.012166,0.031197,0.508988,0.010189,Day 1_AC,AC,Day 1_AC

In [25]:
data.drop_duplicates(subset=["X", "CT_I"], inplace=True)

In [26]:
last_data = data.pivot(index="X", columns="CT_I", values="Log2FC")

In [28]:
last_data.head(5)
print(last_data.shape)

(77978, 16)

In [30]:
last_data.index.name = None
last_data.columns.name = None
last_data

,AC,CHOR,DGGRC,EN,EPEN,FB,MAC,MEGLU,MGL,MSN,NGNBL,OLG,OPC,PEP,TEGLU,TEINH
chr10_100010270_100010770,NaN,NaN,1.363954,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
chr10_100015428_100015928,1.060658,NaN,NaN,NaN,2.068837,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.265627,NaN,NaN
chr10_100019671_100020171,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.20535
chr10_100022052_100022552,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.484384,NaN
chr10_100024658_100025158,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.283250,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
chrX_99819891_99820391,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.042799,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
chrX_99840912_99841412,NaN,NaN,2.551353,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
chrX_99841978_99842478,NaN,NaN,2.375463,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
chrX_99873519_99874019,1.070267,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
chrX_99975185_99975685,NaN,2.134131,NaN,NaN,1.887330,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
last_data[last_data.notna()] = 1
last_data.fillna(0, inplace=True)

In [33]:
last_data.to_csv("/mnt/d/dailywork/Mouse_brain/upset_0430.csv")