In [2]:
import pandas as pd
coro_data = pd.read_csv('coro_data.csv')
coro_data.head(10)

<ipython-input-2-546d572d0884>:2: DtypeWarning: Columns (23,32) have mixed types. Specify dtype option on import or set low_memory=False.
  coro_data = pd.read_csv('coro_data.csv')

,Host,Virus,HostTaxID,VirusTaxID,HostNCBIResolved,VirusNCBIResolved,ICTVRatified,HostGenus,HostFamily,HostOrder,...,PMID,ReleaseYear,ReleaseMonth,ReleaseDay,CollectionYear,CollectionMonth,CollectionDay,AssocID,DatabaseDOI,NCBIAccession
0,NaN,NaN,10114,11118,True,True,False,rattus,muridae,rodentia,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,33554,693996,True,True,False,NaN,NaN,carnivora,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,371929,694002,True,True,False,pitangus,tyrannidae,passeriformes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,49442,694002,True,True,False,rhinolophus,rhinolophidae,chiroptera,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,9397,11118,True,True,False,NaN,NaN,chiroptera,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,9397,693996,True,True,False,NaN,NaN,chiroptera,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,9787,694002,True,True,False,NaN,NaN,perissodactyla,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,9822,693996,True,True,False,sus,suidae,artiodactyla,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,9895,694002,True,True,False,NaN,bovidae,artiodactyla,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,alphacoronavirus 1,33554,693997,True,True,True,NaN,NaN,carnivora,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
# get coroviridae data with NCBIAccession number
id_accession_data = coro_data[['VirusTaxID','NCBIAccession']]
id_accession_data.dropna(inplace=True)

# construct a dictionary, the key of which is ID number and value is NCBIAccession
dic_ID_Accession = {}

for key,value in zip(id_accession_data['VirusTaxID'],id_accession_data['NCBIAccession']):
    process_value = value.split(',') # split the accession number by comma
    dic_ID_Accession[key] = dic_ID_Accession.get(key, []) + process_value

<ipython-input-3-8f9248b656ce>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  id_accession_data.dropna(inplace=True)

In [18]:
IDs = []
Accessions = []

for key, value in dic_ID_Accession.items():
    n_value_count = len(value)
    IDs = IDs + [key]*n_value_count
    Accessions = Accessions + value

coro_id_accession_csv_data = pd.DataFrame(IDs, Accessions)
coro_id_accession_csv_data = coro_id_accession_csv_data.reset_index()
coro_id_accession_csv_data.columns = ['Accession', 'VirusID']

In [21]:
coro_id_accession_csv_data.to_csv('/home/ouconstand/Learning/graduation/virus_host/construct_graph/coro_id_accession.csv',index=None)

In [ ]:
13922800565